# Generated by Django 5.0 on 2024-02-02 22:05

import file_sharing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[file_sharing_app.models.validate_file_extension]),
        ),
    ]
